### ISSUE TITLE
Some General Questions

### ISSUE THREAD

**Issue by dargmuesli** [prodrigestivill/docker-postgres-backup-local#15]
Hey there,

I'm wondering what the `POSTGRES_PORT_5432_TCP_ADDR` variable means. It's undocumented in this repository.

https://github.com/prodrigestivill/docker-postgres-backup-local/blob/7be5d39ad4b54964b5a35086066c72fc7b75e70c/backup.sh#L11-L13

Also one original Postgres variable (`PGPASSWORD`) is set:

https://github.com/prodrigestivill/docker-postgres-backup-local/blob/7be5d39ad4b54964b5a35086066c72fc7b75e70c/backup.sh#L32

why not `PGHOST`, `PGPORT`, `PGUSER`, ...? :)

**Comment by prodrigestivill** [comment]
**Regarding what POSTGRES_PORT_5432_TCP_ADDR variable means, a quick search points out the answer:**

It's related with containers linking, no need for the user to setup anything.
Full explanation: https://stackoverflow.com/questions/27664775/where-do-postgres-port-5432-tcp-addr-and-postgres-port-5432-tcp-port-come-from

**Regarding using POSTGRES_PASSWORD as a docker environment variable instead of PGPASSWORD:**

As the [official postgres image](https://hub.docker.com/_/postgres/) states:

> POSTGRES_PASSWORD:
> This environment variable is recommended for you to use the PostgreSQL image. 

**Regarding using internal environment variables for some settings only:**
Yes, it could be used for most of the config parameters. 
But password is really a sensitive information, so in order to avoid appearing in a process listing of the host machine it is typically used as environment variable.
The rest of information can even be useful when listing processes to identify each backup process.
So no plan to change this for now unless any advantage is provided.



Closing for now, feel free to open for more questions.
