### ISSUE TITLE
No permission to create directories like /backups/daily as user postgres:postgres

### ISSUE THREAD

**Issue by Tromp6** [prodrigestivill/docker-postgres-backup-local#37]
postgres@50890ecd4a99:/$ ./backup.sh
mkdir: cannot create directory ‘/backups/daily/’: Permission denied
mkdir: cannot create directory ‘/backups/weekly/’: Permission denied
mkdir: cannot create directory ‘/backups/monthly/’: Permission denied

**Comment by prodrigestivill** [comment]
Hello @Tromp6,

If you run the as different user, like `postgres` as recommended, the system administrator must initialize the permission of the destination folder as follows:
```sh
# for default images (debian)
mkdir -p /var/opt/pgbackups && chown -R 999:999 /var/opt/pgbackups
# for alpine images
mkdir -p /var/opt/pgbackups && chown -R 70:70 /var/opt/pgbackups
```

This has also been added to README.md.

Thanks for reporting.

**Comment by quevon24** [comment]
Thanks for answering, I'm having the same problem, when I run the commands for alpine mkdir works fine but with chown I have to run it with sudo to make it work, because if don't it throws this error: chown: changing ownership of '/var/opt/pgbackups': Operation not permitted

I don't have postgresql on host, only on container but even running those commands it keeps saying :

2021/07/22 03:39:23 443 cmd: /backup.sh
2021/07/22 03:39:23 443: mkdir: cannot create directory ‘/backups/daily/’
2021/07/22 03:39:23 443: : Permission denied
mkdir: cannot create directory ‘/backups/weekly/’: Permission denied
2021/07/22 03:39:23 443: mkdir: cannot create directory ‘/backups/monthly/’: Permission denied
2021/07/22 03:39:23 443 Exit Status: 1

I'm using a VPS with ubuntu 20.04, Docker version 20.10.7 build f0df350, docker-compose version 1.25.0

I also ran docker-compose exec db /bin/bash and inside it I got uid 70 and gid 70 but even assignin those uid and guid keeps throwing permission denied.
